name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install and test backend
        run: |
          cd backend
          npm ci
          npm test
        env:
          CI: true
      - name: npm install and test frontend
        run: |
          cd frontend
          npm ci
          npm test
        env:
          CI: true
      - name: Build
        run: |
          cd backend
          rm -rf build && cd ../frontend && npm run build --prod && cp -r build ../backend/
      - name: Deploy to heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: |
          git config --global user.email "partanen.joonas@gmail.com"
          git config --global user.name "Joonas Partanen"
          git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git `git subtree split --prefix=backend master`:master --force
