name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install and test backend
        run: |
          cd backend
          npm ci
          npm test
        env:
          CI: true
      - name: npm install and test frontend
        run: |
          cd frontend
          npm ci
          npm test
        env:
          CI: true
      - name: Build
        run: |
          cd backend
          rm -rf build && cd ../frontend && npm run build --prod && cp -r build ../backend/
      - name: Add remote origin
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Deploy to heroku
        run: |
          git config --global user.email "partanen.joonas@gmail.com"
          git config --global user.name "Joonas Partanen"
          git subtree push --prefix=backend heroku origin:master
