name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install and test backend
      run: |
        cd backend
        npm ci
        npm test
      env:
        CI: true
    - name: npm install and test frontend
      run: |
        cd ../frontend
        npm ci
        npm test
      env:
        CI: true
